// The report as a self-contained HTML page (inline styles and images; prints
// to PDF from the browser) and as Markdown (images inline as data URLs).  Both
// are pure: every piece of text is escaped, and only PNG data URLs are taken
// as images.

import { parseBlocks, type Block, type Inline } from "../markdown";
import type { Report, ReportCheck, Verdict } from "./report";

const esc = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const isPng = (url: string): boolean => /^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(url);

const VERDICT_LABEL: Record<Verdict, string> = { pass: "meets its goal", attention: "needs attention", info: "not judged" };

const when = (iso: string): string => {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" });
};

// ---------------------------------------------------------------- Markdown

const mdCell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function mdTable(head: string[], rows: string[][]): string {
  return [
    `| ${head.map(mdCell).join(" | ")} |`,
    `| ${head.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${r.map(mdCell).join(" | ")} |`),
  ].join("\n");
}

export function reportMarkdown(r: Report): string {
  const out: string[] = [];
  out.push(`# ${r.title}`, "");
  out.push(`*${r.kind} · ${when(r.created)} · ${r.model.provider}, ${r.model.model} (${r.model.local ? "local" : "cloud"})*`, "");
  if (r.question) out.push(`> ${r.question.replace(/\n/g, " ")}`, "");

  out.push("## Quality checks", "");
  out.push(mdTable(["Check", "Verdict", "Numbers"], r.checks.map((c) => [c.title, VERDICT_LABEL[c.verdict], c.headline])), "");
  for (const c of r.checks) {
    out.push(`### ${c.title} — ${VERDICT_LABEL[c.verdict]}`, "");
    if (c.goal) out.push(`*Goal:* ${c.goal}`, "");
    out.push(mdTable(["Measure", "Value"], c.details), "");
  }

  if (r.figures.length) {
    out.push("## Figures", "");
    for (const f of r.figures) if (isPng(f.dataUrl)) out.push(`**${f.title}.** ${f.caption}`, "", `![${f.title}](${f.dataUrl})`, "");
  }

  out.push("## Dataset", "");
  out.push(mdTable(["", ""], datasetRows(r)), "");

  if (r.tuning?.length) {
    out.push("## Tuning", "");
    for (const t of r.tuning) {
      out.push(`### ${t.stage}`, "");
      out.push(mdTable(["Trial", "Changes", "Numbers", "Chosen"], t.trials.map((x) => [`#${x.n}`, x.changes, x.headline, x.chosen ? "✓" : ""])), "");
      if (t.why) out.push(`*Why:* ${t.why}`, "");
    }
  }

  if (r.steps.length) {
    out.push("## What the agent did", "");
    out.push(mdTable(["Tool", "Result"], r.steps.map((s) => [s.tool, (s.ok ? "" : "failed: ") + s.summary])), "");
  }

  out.push("## Settings used", "");
  for (const s of r.settings) out.push(`### ${s.stage}`, "", mdTable(["Setting", "Value"], s.values), "");
  if (r.sampleFacts.length) out.push("### Sample facts (set by the user)", "", mdTable(["Setting", "Value"], r.sampleFacts), "");

  if (r.narrative) out.push("## The model's summary", "", "*Written by the model; the numbers above are measured.*", "", r.narrative, "");

  out.push("## Caveats and open issues", "", ...r.caveats.map((c) => `- ${c}`), "");
  out.push("---", "", "*Generated by NEBULA3D's NEBULA Pilot. Tables and figures come from nebula3d's deterministic metrics.*", "");
  return out.join("\n");
}

const datasetRows = (r: Report): [string, string][] =>
  [
    ["Dataset", r.dataset.label],
    ["Raw file", r.dataset.rawName],
    ["Temperature", r.dataset.temperature ?? "–"],
    ["Reciprocal grid", r.dataset.grid ?? "–"],
    ["Ranges", r.dataset.ranges ?? "–"],
    ["Unit cell", r.dataset.cell ?? "–"],
    ["3D-ΔPDF grid", r.dataset.dpdfGrid ?? "–"],
    ["Stage outputs", r.dataset.stages.join(", ") || "–"],
  ] as [string, string][];

// ---------------------------------------------------------------- HTML

function inlineHtml(nodes: Inline[]): string {
  return nodes
    .map((n) => {
      switch (n.type) {
        case "text":
          return esc(n.value);
        case "strong":
          return `<strong>${inlineHtml(n.children)}</strong>`;
        case "em":
          return `<em>${inlineHtml(n.children)}</em>`;
        case "code":
          return `<code>${esc(n.value)}</code>`;
        case "link":
          return /^https?:\/\//.test(n.href) ? `<a href="${esc(n.href)}">${inlineHtml(n.children)}</a>` : inlineHtml(n.children);
      }
    })
    .join("");
}

function blocksHtml(blocks: Block[]): string {
  return blocks
    .map((b) => {
      switch (b.type) {
        case "heading":
          return `<h4>${inlineHtml(b.inline)}</h4>`;
        case "paragraph":
          return `<p>${inlineHtml(b.inline)}</p>`;
        case "code":
          return `<pre>${esc(b.value)}</pre>`;
        case "list":
          return `<${b.ordered ? "ol" : "ul"}>${b.items.map((i) => `<li>${inlineHtml(i)}</li>`).join("")}</${b.ordered ? "ol" : "ul"}>`;
        case "table":
          return `<table><thead><tr>${b.header.map((h) => `<th>${inlineHtml(h)}</th>`).join("")}</tr></thead><tbody>${b.rows
            .map((row) => `<tr>${row.map((c) => `<td>${inlineHtml(c)}</td>`).join("")}</tr>`)
            .join("")}</tbody></table>`;
        case "blockquote":
          return `<blockquote>${inlineHtml(b.inline)}</blockquote>`;
        case "hr":
          return "<hr>";
      }
    })
    .join("\n");
}

const table = (rows: [string, string][], head?: [string, string]): string =>
  `<table class="kv">${head ? `<thead><tr><th>${esc(head[0])}</th><th>${esc(head[1])}</th></tr></thead>` : ""}<tbody>${rows
    .map(([k, v]) => `<tr><th scope="row">${esc(k)}</th><td>${esc(v)}</td></tr>`)
    .join("")}</tbody></table>`;

const chip = (v: Verdict): string => `<span class="chip ${v}">${esc(VERDICT_LABEL[v])}</span>`;

const checkCard = (c: ReportCheck): string =>
  `<div class="card check"><div class="card-head"><h3>${esc(c.title)}</h3>${chip(c.verdict)}</div><p class="headline">${esc(c.headline)}</p></div>`;

const checkSection = (c: ReportCheck): string =>
  `<section class="check-detail"><div class="card-head"><h3>${esc(c.title)}</h3>${chip(c.verdict)}</div>` +
  (c.goal ? `<p class="goal"><span>Goal</span> ${esc(c.goal)}</p>` : "") +
  table(c.details, ["Measure", "Value"]) +
  "</section>";

const STYLE = `
:root { --ink:#1b2230; --muted:#5d6678; --line:#e2e6ee; --paper:#ffffff; --tint:#f5f7fb; --accent:#3d74e0;
  --pass:#17865d; --pass-bg:#e5f5ee; --att:#b26a00; --att-bg:#fdf1de; --info:#5d6678; --info-bg:#eef1f6; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--tint); color: var(--ink);
  font: 14px/1.55 Inter, "Segoe UI", system-ui, -apple-system, Helvetica, Arial, sans-serif; }
.page { max-width: 980px; margin: 0 auto; padding: 40px 36px 56px; background: var(--paper); }
.brand { display: flex; align-items: center; gap: 10px; color: var(--accent); font-weight: 650; letter-spacing: .08em;
  font-size: 11px; text-transform: uppercase; }
.brand i { width: 9px; height: 9px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 0 4px #3d74e022; }
h1 { font-size: 26px; line-height: 1.25; margin: 10px 0 6px; letter-spacing: -.01em; }
.meta { color: var(--muted); font-size: 13px; margin: 0 0 18px; }
.meta b { color: var(--ink); font-weight: 600; }
.request { border-left: 3px solid var(--accent); background: var(--tint); padding: 10px 14px; border-radius: 0 8px 8px 0;
  margin: 0 0 26px; color: #2b3445; }
h2 { font-size: 17px; margin: 34px 0 12px; padding-bottom: 6px; border-bottom: 1px solid var(--line); }
h3 { font-size: 14.5px; margin: 0; }
h4 { font-size: 14px; margin: 14px 0 6px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 12px; }
.card { border: 1px solid var(--line); border-radius: 10px; padding: 12px 14px; background: var(--paper); }
.card-head { display: flex; align-items: center; justify-content: space-between; gap: 10px; margin-bottom: 6px; }
.headline { margin: 0; color: #2b3445; font-variant-numeric: tabular-nums; font-size: 13px; }
.chip { font-size: 11px; font-weight: 650; border-radius: 999px; padding: 2px 9px; white-space: nowrap; }
.chip.pass { color: var(--pass); background: var(--pass-bg); }
.chip.attention { color: var(--att); background: var(--att-bg); }
.chip.info { color: var(--info); background: var(--info-bg); }
.check-detail { margin: 0 0 18px; break-inside: avoid; }
.goal { color: var(--muted); font-size: 12.5px; margin: 4px 0 8px; }
.goal span { display: inline-block; font-size: 10.5px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase;
  color: var(--accent); margin-right: 4px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; font-variant-numeric: tabular-nums; margin: 4px 0 6px; }
th, td { text-align: left; padding: 6px 9px; border-bottom: 1px solid var(--line); vertical-align: top; }
thead th { font-size: 11px; letter-spacing: .05em; text-transform: uppercase; color: var(--muted); font-weight: 650; }
table.kv th[scope=row] { width: 38%; color: var(--muted); font-weight: 500; }
tbody tr:nth-child(even) td, tbody tr:nth-child(even) th[scope=row] { background: #fafbfd; }
.figures { display: grid; grid-template-columns: repeat(auto-fill, minmax(210px, 1fr)); gap: 14px; }
figure { margin: 0; break-inside: avoid; }
figure img { width: 100%; border-radius: 8px; border: 1px solid var(--line); background: #0d1117; display: block; }
figcaption { font-size: 12px; color: var(--muted); margin-top: 5px; }
figcaption b { color: var(--ink); }
.why { color: var(--muted); font-size: 12.5px; margin: 2px 0 14px; }
.narrative { border: 1px solid var(--line); border-radius: 10px; padding: 4px 16px; }
.note { color: var(--muted); font-size: 12px; font-style: italic; }
ul.caveats li { margin: 4px 0; }
pre { background: var(--tint); padding: 8px 10px; border-radius: 6px; overflow-x: auto; }
code { background: var(--tint); padding: 1px 4px; border-radius: 4px; font-size: 12.5px; }
footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
@media print { body { background: #fff; } .page { padding: 0; max-width: none; } h2 { break-after: avoid; } }
`;

export function reportHtml(r: Report): string {
  const figures = r.figures.filter((f) => isPng(f.dataUrl));
  const parts: string[] = [];
  parts.push(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">`);
  parts.push(`<title>${esc(r.title)}</title><style>${STYLE}</style></head><body><main class="page">`);
  parts.push(`<div class="brand"><i></i>NEBULA3D · NEBULA Pilot report</div>`);
  parts.push(`<h1>${esc(r.dataset.label)}</h1>`);
  parts.push(
    `<p class="meta"><b>${esc(r.kind)}</b> · ${esc(when(r.created))} · ${esc(r.model.provider)}, <b>${esc(r.model.model)}</b> (${r.model.local ? "local" : "cloud"})</p>`,
  );
  if (r.question) parts.push(`<div class="request">${esc(r.question)}</div>`);

  parts.push(`<h2>Quality checks</h2><div class="grid">${r.checks.map(checkCard).join("")}</div>`);

  if (figures.length) {
    parts.push(
      `<h2>Figures</h2><div class="figures">${figures
        .map((f) => `<figure><img src="${f.dataUrl}" alt="${esc(f.title)}"><figcaption><b>${esc(f.title)}.</b> ${esc(f.caption)}</figcaption></figure>`)
        .join("")}</div>`,
    );
  }

  parts.push(`<h2>The checks in detail</h2>${r.checks.map(checkSection).join("")}`);
  parts.push(`<h2>Dataset</h2>${table(datasetRows(r))}`);

  if (r.tuning?.length) {
    parts.push("<h2>Tuning</h2>");
    for (const t of r.tuning) {
      parts.push(`<h4>${esc(t.stage)}</h4><table><thead><tr><th>Trial</th><th>Changes</th><th>Numbers</th><th>Chosen</th></tr></thead><tbody>`);
      parts.push(t.trials.map((x) => `<tr><td>#${x.n}</td><td>${esc(x.changes)}</td><td>${esc(x.headline)}</td><td>${x.chosen ? "✓" : ""}</td></tr>`).join(""));
      parts.push(`</tbody></table>${t.why ? `<p class="why">${esc(t.why)}</p>` : ""}`);
    }
  }

  if (r.steps.length) {
    parts.push(
      `<h2>What the agent did</h2><table><thead><tr><th>Tool</th><th>Result</th></tr></thead><tbody>${r.steps
        .map((s) => `<tr><td><code>${esc(s.tool)}</code></td><td>${s.ok ? "" : "<b>failed:</b> "}${esc(s.summary)}</td></tr>`)
        .join("")}</tbody></table>`,
    );
  }

  parts.push(`<h2>Settings used</h2><div class="grid">`);
  for (const s of r.settings) parts.push(`<div class="card"><h3>${esc(s.stage)}</h3>${table(s.values)}</div>`);
  if (r.sampleFacts.length) parts.push(`<div class="card"><h3>Sample facts (set by the user)</h3>${table(r.sampleFacts)}</div>`);
  parts.push("</div>");

  if (r.narrative) {
    parts.push(`<h2>The model's summary</h2><p class="note">Written by the model; the numbers above are measured.</p>`);
    parts.push(`<div class="narrative">${blocksHtml(parseBlocks(r.narrative))}</div>`);
  }

  parts.push(`<h2>Caveats and open issues</h2><ul class="caveats">${r.caveats.map((c) => `<li>${esc(c)}</li>`).join("")}</ul>`);
  parts.push(
    `<footer>Generated by NEBULA3D's NEBULA Pilot on ${esc(when(r.created))}. Tables and figures come from nebula3d's deterministic metrics; the summary is the model's.</footer>`,
  );
  parts.push("</main></body></html>");
  return parts.join("\n");
}
